In [1]:
import csv
import pandas as pd
from datetime import datetime

In [2]:
from pymongo import MongoClient

client = MongoClient("mongodb://localhost:27017/")
db = client["boston_housing"]
print("Connected!", client.list_database_names())

Connected! ['admin', 'boston_housing', 'config', 'local', 'nwsl']

In [3]:
# load permits
permits = pd.read_csv('permits.csv', dtype={'zip':str})
permits.head()

,permitnumber,worktype,permittypedescr,description,comments,applicant,declared_valuation,total_fees,issued_date,expiration_date,...,city,state,zip,ward,property_id,parcel_id,gpsy,gpsx,y_latitude,x_longitude
0,A1000569,INTEXT,Amendment to a Long Form,Interior/Exterior Work,This work is to Amend Permit ALT347244. Elimin...,Patrick Sharkey,"$36,500.00",$390.00,2021-01-28 16:29:26+00,2021-07-28 04:00:00+00,...,Boston,MA,02109,3.0,130392.0,3.038070e+08,2.956235e+06,777000.467910,42.359190,-71.052924
1,A100071,COB,Amendment to a Long Form,City of Boston,Change connector link layout from attached enc...,Renee Santeusanio,"$40,000.00",$29.00,2011-11-04 15:04:58+00,2012-05-04 04:00:00+00,...,West Roxbury,MA,02132,20.0,17268.0,2.012032e+09,2.920239e+06,751016.119617,42.260750,-71.149610
2,A1001012,OTHER,Amendment to a Long Form,Other,Amend Alt943748 to erect a roof deck as per pl...,Jusimar Oliveria,"$5,000.00",$70.00,2020-06-01 18:08:47+00,NaN,...,Charlestown,MA,02129,2.0,113443.0,2.028370e+08,2.962078e+06,775710.380595,42.375243,-71.057585
3,A1001201,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Build steel balcony over garden level with sta...,Andreas Hwang,"$74,295.75",$803.00,2019-11-13 18:38:56+00,2020-05-13 04:00:00+00,...,Roxbury,MA,02118,4.0,129994.0,4.025580e+08,2.949423e+06,769648.312667,42.340600,-71.080250
4,A100137,EXTREN,Amendment to a Long Form,Renovations - Exterior,Landscaping/stonework - amending permit #2801/...,NaN,"$15,000.00",$182.00,2013-01-03 19:13:09+00,2013-07-03 04:00:00+00,...,Brighton,MA,02135,22.0,149852.0,2.204944e+09,2.950791e+06,749690.298777,42.344600,-71.154050

In [4]:
permits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720177 entries, 0 to 720176
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   permitnumber        720177 non-null  object
 1   worktype            715358 non-null  object
 2   permittypedescr     720177 non-null  object
 3   description         715358 non-null  object
 4   comments            719934 non-null  object
 5   applicant           708567 non-null  object
 6   declared_valuation  720177 non-null  object
 7   total_fees          720177 non-null  object
 8   issued_date         720177 non-null  object
 9   expiration_date     689384 non-null  object
 10  status              720177 non-null  object
 11  occupancytype       718129 non-null  object
 12  sq_feet             720177 non-null  float64
 13  address             710752 non-null  object
 14  city                720023 non-null  object
 15  state               720177 non-null  object
 16  zip                 719861 non-null  object
 17  ward                720032 non-null  float64
 18  property_id         708345 non-null  float64
 19  parcel_id           707585 non-null  float64
 20  gpsy                704692 non-null  float64
 21  gpsx                704692 non-null  float64
 22  y_latitude          704692 non-null  float64
 23  x_longitude         704692 non-null  float64
dtypes: float64(8), object(16)
memory usage: 131.9+ MB

In [5]:
# drop na 
permits.dropna(inplace=True)
permits.info()

<class 'pandas.core.frame.DataFrame'>
Index: 649232 entries, 0 to 720176
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   permitnumber        649232 non-null  object
 1   worktype            649232 non-null  object
 2   permittypedescr     649232 non-null  object
 3   description         649232 non-null  object
 4   comments            649232 non-null  object
 5   applicant           649232 non-null  object
 6   declared_valuation  649232 non-null  object
 7   total_fees          649232 non-null  object
 8   issued_date         649232 non-null  object
 9   expiration_date     649232 non-null  object
 10  status              649232 non-null  object
 11  occupancytype       649232 non-null  object
 12  sq_feet             649232 non-null  float64
 13  address             649232 non-null  object
 14  city                649232 non-null  object
 15  state               649232 non-null  object
 16  zip                 649232 non-null  object
 17  ward                649232 non-null  float64
 18  property_id         649232 non-null  float64
 19  parcel_id           649232 non-null  float64
 20  gpsy                649232 non-null  float64
 21  gpsx                649232 non-null  float64
 22  y_latitude          649232 non-null  float64
 23  x_longitude         649232 non-null  float64
dtypes: float64(8), object(16)
memory usage: 123.8+ MB

about 8k rows were dropped

In [6]:
# convert money into float

permits['declared_valuation'] = permits['declared_valuation'].str.replace("$","").str.replace(",","")

permits.head()

,permitnumber,worktype,permittypedescr,description,comments,applicant,declared_valuation,total_fees,issued_date,expiration_date,...,city,state,zip,ward,property_id,parcel_id,gpsy,gpsx,y_latitude,x_longitude
0,A1000569,INTEXT,Amendment to a Long Form,Interior/Exterior Work,This work is to Amend Permit ALT347244. Elimin...,Patrick Sharkey,36500.00,$390.00,2021-01-28 16:29:26+00,2021-07-28 04:00:00+00,...,Boston,MA,02109,3.0,130392.0,3.038070e+08,2.956235e+06,777000.467910,42.35919,-71.052924
1,A100071,COB,Amendment to a Long Form,City of Boston,Change connector link layout from attached enc...,Renee Santeusanio,40000.00,$29.00,2011-11-04 15:04:58+00,2012-05-04 04:00:00+00,...,West Roxbury,MA,02132,20.0,17268.0,2.012032e+09,2.920239e+06,751016.119617,42.26075,-71.149610
3,A1001201,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Build steel balcony over garden level with sta...,Andreas Hwang,74295.75,$803.00,2019-11-13 18:38:56+00,2020-05-13 04:00:00+00,...,Roxbury,MA,02118,4.0,129994.0,4.025580e+08,2.949423e+06,769648.312667,42.34060,-71.080250
5,A1001913,INTREN,Amendment to a Long Form,Renovations - Interior NSC,Amendment to issued permit ALT888985. relocate...,Xhaklina Desmond,1.00,$33.00,2019-10-18 13:21:00+00,2020-04-18 04:00:00+00,...,Allston,MA,02134,21.0,20073.0,2.100846e+09,2.953789e+06,755678.944280,42.35276,-71.131850
6,A1002445,INTREN,Amendment to a Long Form,Renovations - Interior NSC,"Install new beam in basement, sister joists to...",Richard Hester,50000.00,$556.00,2019-11-12 16:00:03+00,2020-05-12 04:00:00+00,...,Allston,MA,02134,22.0,3077.0,2.200085e+09,2.956331e+06,757700.459594,42.35971,-71.124330

In [7]:
# Source - https://stackoverflow.com/a/26763793
# Posted by chrisb, modified by community. See post 'Timeline' for change history
# Retrieved 2026-04-12, License - CC BY-SA 4.0 - AI as well

# converting permit issue data into only the date and removing the exact time since i don't need that
permits['issued_date'] = pd.to_datetime(permits['issued_date'].str[:10], format='%Y-%m-%d', errors='coerce')
permits.head()

,permitnumber,worktype,permittypedescr,description,comments,applicant,declared_valuation,total_fees,issued_date,expiration_date,...,city,state,zip,ward,property_id,parcel_id,gpsy,gpsx,y_latitude,x_longitude
0,A1000569,INTEXT,Amendment to a Long Form,Interior/Exterior Work,This work is to Amend Permit ALT347244. Elimin...,Patrick Sharkey,36500.00,$390.00,2021-01-28,2021-07-28 04:00:00+00,...,Boston,MA,02109,3.0,130392.0,3.038070e+08,2.956235e+06,777000.467910,42.35919,-71.052924
1,A100071,COB,Amendment to a Long Form,City of Boston,Change connector link layout from attached enc...,Renee Santeusanio,40000.00,$29.00,2011-11-04,2012-05-04 04:00:00+00,...,West Roxbury,MA,02132,20.0,17268.0,2.012032e+09,2.920239e+06,751016.119617,42.26075,-71.149610
3,A1001201,INTEXT,Amendment to a Long Form,Interior/Exterior Work,Build steel balcony over garden level with sta...,Andreas Hwang,74295.75,$803.00,2019-11-13,2020-05-13 04:00:00+00,...,Roxbury,MA,02118,4.0,129994.0,4.025580e+08,2.949423e+06,769648.312667,42.34060,-71.080250
5,A1001913,INTREN,Amendment to a Long Form,Renovations - Interior NSC,Amendment to issued permit ALT888985. relocate...,Xhaklina Desmond,1.00,$33.00,2019-10-18,2020-04-18 04:00:00+00,...,Allston,MA,02134,21.0,20073.0,2.100846e+09,2.953789e+06,755678.944280,42.35276,-71.131850
6,A1002445,INTREN,Amendment to a Long Form,Renovations - Interior NSC,"Install new beam in basement, sister joists to...",Richard Hester,50000.00,$556.00,2019-11-12,2020-05-12 04:00:00+00,...,Allston,MA,02134,22.0,3077.0,2.200085e+09,2.956331e+06,757700.459594,42.35971,-71.124330

In [8]:
# only keep the cols that i need
permits = permits[['permittypedescr', 'declared_valuation', 'issued_date', 'occupancytype', 'sq_feet', 'zip', 'y_latitude', 'x_longitude']]
permits.head()

,permittypedescr,declared_valuation,issued_date,occupancytype,sq_feet,zip,y_latitude,x_longitude
0,Amendment to a Long Form,36500.00,2021-01-28,Mixed,0.0,02109,42.35919,-71.052924
1,Amendment to a Long Form,40000.00,2011-11-04,Comm,170.0,02132,42.26075,-71.149610
3,Amendment to a Long Form,74295.75,2019-11-13,Multi,0.0,02118,42.34060,-71.080250
5,Amendment to a Long Form,1.00,2019-10-18,Comm,0.0,02134,42.35276,-71.131850
6,Amendment to a Long Form,50000.00,2019-11-12,1-2FAM,0.0,02134,42.35971,-71.124330

In [9]:
db['permits'].drop()
db['permits'].insert_many(permits.to_dict('records'))
print(f"Loaded {db['permits'].count_documents({})} permits into MongoDB")

Loaded 649232 permits into MongoDB

***zillow rentals***

In [10]:
rentals = pd.read_csv('rentals.csv', dtype={'RegionName':str})
rentals.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2015-01-31,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
0,91982,1,77494,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County,1420.507342,...,1782.499646,1779.950184,1780.875318,1780.664082,1780.573655,1777.942681,1774.195029,1773.029661,1764.719028,1753.765121
1,61148,2,08701,zip,NJ,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2368.181545,2312.500000
2,91940,3,77449,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Harris County,1253.790752,...,1832.217107,1828.079301,1831.087306,1825.916628,1828.746942,1830.701126,1826.103427,1825.645193,1813.698508,1805.233033
3,91733,5,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,1108.371999,...,1578.575345,1579.556332,1583.791525,1591.838295,1592.101115,1578.987541,1568.584070,1561.960424,1564.160751,1554.245049
4,93144,6,79936,zip,TX,TX,El Paso,"El Paso, TX",El Paso County,NaN,...,1432.882049,1434.855791,1440.499183,1448.393363,1455.099899,1460.361677,1455.365768,1451.221624,1443.924176,1447.231294

In [11]:
# only boston rentals
rentals = rentals[rentals['City'] == 'Boston']
rentals.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2015-01-31,...,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28
560,58638,581,02124,zip,MA,MA,Boston,"Boston-Cambridge-Newton, MA-NH",Suffolk County,NaN,...,2966.099364,2981.781636,2982.411860,2985.425698,2993.505124,3007.286453,3052.233667,3041.629488,3053.583734,3039.320513
1236,58642,1287,02128,zip,MA,MA,Boston,"Boston-Cambridge-Newton, MA-NH",Suffolk County,NaN,...,3046.883860,3057.543911,3079.117570,3068.964890,3065.392556,3047.877271,3062.930615,3056.912363,3047.421790,3036.723165
1372,58649,1428,02135,zip,MA,MA,Boston,"Boston-Cambridge-Newton, MA-NH",Suffolk County,1945.888971,...,2953.336349,2959.751680,2964.140178,2969.517151,2980.443531,2998.525639,3003.262951,3022.992186,3029.144761,3043.389521
1757,58644,1834,02130,zip,MA,MA,Boston,"Boston-Cambridge-Newton, MA-NH",Suffolk County,1972.695870,...,3235.864404,3230.166178,3226.502277,3206.170016,3231.465506,3252.742787,3269.678856,3250.591910,3223.731715,3210.367725
1894,58650,1976,02136,zip,MA,MA,Boston,"Boston-Cambridge-Newton, MA-NH",Suffolk County,NaN,...,2491.427561,2508.027261,2507.330936,2518.023981,2523.090582,2546.052411,2548.368823,2566.412081,2532.752085,2588.055556

In [12]:
rentals.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27 entries, 560 to 7648
Columns: 143 entries, RegionID to 2026-02-28
dtypes: float64(134), int64(2), object(7)
memory usage: 30.4+ KB

In [13]:
db["rent_prices"].drop()

for _, row in rentals.iterrows():
    ''' reshaping the date columns because right now, the each date column have prices in them.
    to make it better for mongodb i want them to be nested. used AI a lot in here to help through the loops '''
    
    rent_history = []
    for col in rentals.columns:
        if col.startswith("20"):
            val = row[col]
            if pd.notna(val):
                rent_history.append({
                    'date': datetime.strptime(col, "%Y-%m-%d"),
                    'rent': round(float(val), 2)
                })

    doc = {
    'zip': str(row['RegionName']).zfill(5),
    'city': row.get('City', 'Boston'),
    'metro': row.get('Metro', ''),
    'county': row.get('CountyName', ''),
    'rent_history': sorted(rent_history, key=lambda x: x['date']),
    'data_ovrtm': len(rent_history)
    }
    
    db["rent_prices"].insert_one(doc)

print(f"Loaded {db['rent_prices'].count_documents({})} ZIP codes into MongoDB")

Loaded 27 ZIP codes into MongoDB